orbs:
  artifactory-orb: jfrog/artifactory-orb@1.0.1
version: 2.1
workflows:
  publish:
    jobs:
      - artifactory-orb/upload:
          build-steps:
            - run: npm i
            - run: npm pack
          docker: cimg/node:14.16.1
          name: npm pack
          source: lib
          target: arqapps-2021-npm-local/
