orbs:
  artifactory-orb: jfrog/artifactory-orb@1.0.1
version: 2.1



workflows:
  publish:
      - artifactory-orb/upload:
          build-steps:
            - run: npm i
          docker: cimg/node:14.16.1
          name: npm pack
          source: "*.tgz"
          target: "arqapps-2021-npm/.npm"
