orbs:
  artifactory: circleci/artifactory@1.0.0
version: 2.1
workflows:
  publish:
    jobs:
      - artifactory/upload:
          build-steps:
            - run: npm pack
          docker: cimg/node:14.16.1
          name: npm pack
          source: lib
          target: arqapps-2021-npm/.npm
