defaults: &defaults
  working_directory: ~/rn-aa-lib
  docker:
    - image: circleci/node:10.20.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
  # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/rn-aa-lib
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/rn-aa-lib
      - run:
          name: Set registry URL
          command: npm set registry https://arqapp2021.jfrog.io/artifactory/arqapps-2021-npm/
      - run:
          name: Authenticate with registry
          command: npm login
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
